### ISSUE TITLE
I don't want to use autofac, what can I do? 

### ISSUE THREAD

**Issue by burdier** [sayganov/EventBus.RabbitMQ.Standard#2]
I want to use this NuGet in an existing project.

**Comment by sayganov** [comment]
Hi @burdier,
Currently, it's not possible to use the package without Autofac.

If you decide to go with Autofac you'll need to get done only 2 steps:
1. Install the package `Autofac.Extensions.DependencyInjection`
2. Add `.UseServiceProviderFactory(new AutofacServiceProviderFactory())` to the `CreateHostBuilder `method in Program.cs

**Comment by burdier** [comment]
Thanks for your reply.
